backend:
  name: github
  repo: amresha/amresha-official
  
publish_mode: editorial_workflow
media_folder: content/assets
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: featuredimage, label: Featured Image, widget: image }
      - { name: body, label: Body, widget: markdown }
